language: ruby
rvm:
  - 2.1
install: gem install s3_website && bundle install
script: jekyll build
after_success: 
  - bash postbuild.sh
  - s3_website push
notifications:
    slack: aiacc:DQJx1jxSipYMHzXBVtf4kMGH