---
title: AIA Night of Champions
timezone: UTC
collections:
  inductees:
    title: Inductees
    output: true
  media:
    title: Media
    output: true
  posts:
    title: Posts
    output: true
  sponsors:
    title: Sponsors
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    byLine: ''
    layout: page
    description: 
- scope:
    path: ''
    type: inductees
  values:
    image: 
    layout: inductee
    year: 
- scope:
    path: ''
    type: sponsors
  values:
    image: 
    level: 
exclude:
- "/vendor/"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: Celebrating the Induction to the Hall of Faith
url: 
baseurl: 
cover: "/assets/cover.png"
logo: "/assets/logo.png"
markdown: kramdown
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
EventDate: Saturday, May 15, 2018
